### ISSUE TITLE
✨ **Welcome to Move.it Project** ✨

### ISSUE THREAD

**Issue by caiohenrique-developer** [caiohenrique-developer/moveit-web#10]
#### Roadmap :gem:

- [x] Countdown
  - [x] Restart countdown
- [x] Challenges
  - [x] Completed or failed challenges
- [x] Levels
- [x] Experience
- [x] Pop-up congratulations
- [x] Responsive
- [x] Effects & Animations
- [x] Dark mode (default), Light mode toggle
- [x] Change your avatar and profile name
